charset_comment_filter = require("charset_comment_filter") --Unicode分区提示
candidate_shadow_filter = require("candidate_shadow_filter") --多滤镜候选压成单层，保留满码顶屏
number_translator = require("number")
lua_unicode_display_filter = require("unicode_display")  --Unicode编码提示
calculator_translator = require("calculator_translator")  --简易计算器
exe_processor = require("exe")  -- 网页启动器
shijian2_translator = require("shijian2") -- 高级时间
symbol_hint_translator = require("symbol_hint") --反斜杠符号提示
table_export = require("table_export") --词库导出命令
rime_skin_editor = require("rime_skin_editor") --皮肤编辑器入口
